[variables]
UPLOAD_MAX_FILESIZE = "10M"
POST_MAX_SIZE = "12M"
MEMORY_LIMIT = "256M"

[phases.setup]
nixPkgs = ["...", "php82", "php82Extensions.redis"]

[phases.build]
cmds = ["composer install --no-dev"]

[start]
cmd = "php -d upload_max_filesize=20M -d post_max_size=25M -d memory_limit=512M -d max_execution_time=120 -d max_input_time=120 -d max_file_uploads=50 artisan serve --host=0.0.0.0 --port=$PORT"